### ISSUE TITLE
Add frequency data

### ISSUE THREAD

**Issue by hugolpz** [hugolpz/WeSpeaxExos#3]
### Phase 1 : Unilex data
Frequency lists will be fundamental to your algorithms. This field is known for data of very variable quality. So you may want a code which can easily change input data as cleaner lists may be found later on the web. Some key projects to create your demonstrators :
- https://github.com/unicode-org/unilex/tree/main/data/frequency -- row data from Google smart input suggestion project
- https://github.com/lingua-libre/unilex-extended/tree/main/frequency-sorted-count -- same, cleaner.
FR, EN, AR, JA, ZH are there. There are also better frequency lists but I have to look for them online.

I (Yug) will add Unilex data to the repository.

### Phase 2 : academic grade lists
I (Yug) will add Subtlex data to the repository.

### Progresses
- [x] Phase 1: Unilex https://github.com/hugolpz/WeSpeaxExos/commit/beec672dfd6226582643a6020dcac2a974fcc596 : ar, fr, hi, ja. Missing: en, zh.
- [x] Phase 2: Subtlex

**Comment by Sarveshmeenwa** [comment]
Sarvesh summary : 

- Used Textstat library in python to calculate phrase difficulties
- Textstat has many metrics, most tailored for English. However, the Flesch Reading Ease metric supports other languages as below 
![image](https://user-images.githubusercontent.com/65787323/193072359-9724dfad-c42f-495e-b69f-5ef5f0044e59.png)
- Most are Latin languages, however it does support Arabic using OSMAN metric
- OSMAN score for text (Designed for Arabic, an adaption of Flesch and Fog Formula. Introduces a new factor called "Faseeh".) Using this [acedemic paper](https://aclanthology.org/L16-1038.pdf)
- Harder to find unified method for all languages especially low-resource language but this is still a work in progress
- Current demo (code & csv files uploaded) shows the Flesch Reading Ease score, however for English since there are many more, we could change to others, code is ready-made and adaptable to do so for English. (NOTE: Some pre-processing was required to calculate the English level difficulty score since the row text data had to be adapted according to its objective (Vocabulary,grammar, verb conjugation )
- The English dataset may need to be further cleaned depending on requirements of Airtable.

**Comment by hugolpz** [comment]
### English 
* [Subtlex-US](https://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexus)

### Chinese
- [x] [Subtlex-CH](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0010729)

**Comment by hugolpz** [comment]
@Sarveshmeenwa , depending of your findings and as you see fit, this issue could be reopen.
